"""
report.py

Builds a markdown audit report from structured findings.
"""

from .schemas import SOPRecord, Finding


def build_report(
    sop_records: list[SOPRecord],
    graph: dict,
    findings: list[Finding],
) -> str:
    errors   = [f for f in findings if f.severity == "ERROR"]
    warnings = [f for f in findings if f.severity == "WARNING"]
    infos    = [f for f in findings if f.severity == "INFO"]
    passes   = [f for f in infos if f.rule == "sop_check_pass"]
    other_infos = [f for f in infos if f.rule != "sop_check_pass"]

    lines = [
        "# P&ID Audit Report",
        "",
        "## Summary",
        f"- **Nodes extracted**: {graph['node_count']}",
        f"- **Edges extracted**: {graph['edge_count']}",
        f"- **SOP equipment records**: {len(sop_records)}",
        f"- **Findings**: {len(errors)} errors, {len(warnings)} warnings, {len(infos)} info",
        f"- **Passes**: {len(passes)} SOP checks passed",
        "",
    ]

    lines += ["## SOP Equipment Limits", ""]
    lines += ["| Equipment | Max Pressure (PSIG) | Temp Range (°F) |", "|---|---|---|"]
    for r in sop_records:
        if r.temperature_min_f != r.temperature_max_f:
            temp = f"{r.temperature_min_f} to {r.temperature_max_f}"
        else:
            temp = str(r.temperature_max_f)
        lines.append(f"| {r.raw_name} | {r.pressure_psig} | {temp} |")

    if errors:
        lines += ["", "## Errors", ""]
        for f in errors:
            lines.append(f"**[{f.equipment_id}]** {f.detail}")
            if f.sop_value and f.pid_value:
                lines.append(f"  - SOP: `{f.sop_value}` | P&ID: `{f.pid_value}`")

    if warnings:
        lines += ["", "## Warnings", ""]
        for f in warnings:
            lines.append(f"**[{f.equipment_id}]** {f.detail}")
            if f.sop_value and f.pid_value:
                lines.append(f"  - SOP: `{f.sop_value}` | P&ID: `{f.pid_value}`")

    if passes:
        lines += ["", "## Passes", ""]
        for f in passes:
            lines.append(f"- `{f.equipment_id}` — {f.detail}")

    if other_infos:
        lines += ["", "## Info", ""]
        for f in other_infos:
            lines.append(f"- `{f.equipment_id}` — {f.detail}")

    lines += ["", "---", "_Generated by P&ID Audit Pipeline_"]
    return "\n".join(lines)
